# coding=utf-8
# Copyright, 2021 Ontocord, LLC, All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class OntologyBuilderData:
  
  """ Predefined preliminary labels  """

  #from https://github.com/madisonmay/CommonRegex/blob/master/commonregex.py which is under the MIT License
  # see also for ICD https://stackoverflow.com/questions/5590862/icd9-regex-pattern - but this could be totally wrong!
  # we do regex in this order in order to not capture ner inside domain names and email addresses.
  default_ner_regexes = [
    ("DOMAIN_NAME"     , '(?i)((?:https?://|www\d{0,3}[.])?[a-z0-9.\-]+[.](?:(?:international)|(?:construction)|(?:contractors)|(?:enterprises)|(?:photography)|(?:immobilien)|(?:management)|(?:technology)|(?:directory)|(?:education)|(?:equipment)|(?:institute)|(?:marketing)|(?:solutions)|(?:builders)|(?:clothing)|(?:computer)|(?:democrat)|(?:diamonds)|(?:graphics)|(?:holdings)|(?:lighting)|(?:plumbing)|(?:training)|(?:ventures)|(?:academy)|(?:careers)|(?:company)|(?:domains)|(?:florist)|(?:gallery)|(?:guitars)|(?:holiday)|(?:kitchen)|(?:recipes)|(?:shiksha)|(?:singles)|(?:support)|(?:systems)|(?:agency)|(?:berlin)|(?:camera)|(?:center)|(?:coffee)|(?:estate)|(?:kaufen)|(?:luxury)|(?:monash)|(?:museum)|(?:photos)|(?:repair)|(?:social)|(?:tattoo)|(?:travel)|(?:viajes)|(?:voyage)|(?:build)|(?:cheap)|(?:codes)|(?:dance)|(?:email)|(?:glass)|(?:house)|(?:ninja)|(?:photo)|(?:shoes)|(?:solar)|(?:today)|(?:aero)|(?:arpa)|(?:asia)|(?:bike)|(?:buzz)|(?:camp)|(?:club)|(?:coop)|(?:farm)|(?:gift)|(?:guru)|(?:info)|(?:jobs)|(?:kiwi)|(?:land)|(?:limo)|(?:link)|(?:menu)|(?:mobi)|(?:moda)|(?:name)|(?:pics)|(?:pink)|(?:post)|(?:rich)|(?:ruhr)|(?:sexy)|(?:tips)|(?:wang)|(?:wien)|(?:zone)|(?:biz)|(?:cab)|(?:cat)|(?:ceo)|(?:com)|(?:edu)|(?:gov)|(?:int)|(?:mil)|(?:net)|(?:onl)|(?:org)|(?:pro)|(?:red)|(?:tel)|(?:uno)|(?:xxx)|(?:ac)|(?:ad)|(?:ae)|(?:af)|(?:ag)|(?:ai)|(?:al)|(?:am)|(?:an)|(?:ao)|(?:aq)|(?:ar)|(?:as)|(?:at)|(?:au)|(?:aw)|(?:ax)|(?:az)|(?:ba)|(?:bb)|(?:bd)|(?:be)|(?:bf)|(?:bg)|(?:bh)|(?:bi)|(?:bj)|(?:bm)|(?:bn)|(?:bo)|(?:br)|(?:bs)|(?:bt)|(?:bv)|(?:bw)|(?:by)|(?:bz)|(?:ca)|(?:cc)|(?:cd)|(?:cf)|(?:cg)|(?:ch)|(?:ci)|(?:ck)|(?:cl)|(?:cm)|(?:cn)|(?:co)|(?:cr)|(?:cu)|(?:cv)|(?:cw)|(?:cx)|(?:cy)|(?:cz)|(?:de)|(?:dj)|(?:dk)|(?:dm)|(?:do)|(?:dz)|(?:ec)|(?:ee)|(?:eg)|(?:er)|(?:es)|(?:et)|(?:eu)|(?:fi)|(?:fj)|(?:fk)|(?:fm)|(?:fo)|(?:fr)|(?:ga)|(?:gb)|(?:gd)|(?:ge)|(?:gf)|(?:gg)|(?:gh)|(?:gi)|(?:gl)|(?:gm)|(?:gn)|(?:gp)|(?:gq)|(?:gr)|(?:gs)|(?:gt)|(?:gu)|(?:gw)|(?:gy)|(?:hk)|(?:hm)|(?:hn)|(?:hr)|(?:ht)|(?:hu)|(?:id)|(?:ie)|(?:il)|(?:im)|(?:in)|(?:io)|(?:iq)|(?:ir)|(?:is)|(?:it)|(?:je)|(?:jm)|(?:jo)|(?:jp)|(?:ke)|(?:kg)|(?:kh)|(?:ki)|(?:km)|(?:kn)|(?:kp)|(?:kr)|(?:kw)|(?:ky)|(?:kz)|(?:la)|(?:lb)|(?:lc)|(?:li)|(?:lk)|(?:lr)|(?:ls)|(?:lt)|(?:lu)|(?:lv)|(?:ly)|(?:ma)|(?:mc)|(?:md)|(?:me)|(?:mg)|(?:mh)|(?:mk)|(?:ml)|(?:mm)|(?:mn)|(?:mo)|(?:mp)|(?:mq)|(?:mr)|(?:ms)|(?:mt)|(?:mu)|(?:mv)|(?:mw)|(?:mx)|(?:my)|(?:mz)|(?:na)|(?:nc)|(?:ne)|(?:nf)|(?:ng)|(?:ni)|(?:nl)|(?:no)|(?:np)|(?:nr)|(?:nu)|(?:nz)|(?:om)|(?:pa)|(?:pe)|(?:pf)|(?:pg)|(?:ph)|(?:pk)|(?:pl)|(?:pm)|(?:pn)|(?:pr)|(?:ps)|(?:pt)|(?:pw)|(?:py)|(?:qa)|(?:re)|(?:ro)|(?:rs)|(?:ru)|(?:rw)|(?:sa)|(?:sb)|(?:sc)|(?:sd)|(?:se)|(?:sg)|(?:sh)|(?:si)|(?:sj)|(?:sk)|(?:sl)|(?:sm)|(?:sn)|(?:so)|(?:sr)|(?:st)|(?:su)|(?:sv)|(?:sx)|(?:sy)|(?:sz)|(?:tc)|(?:td)|(?:tf)|(?:tg)|(?:th)|(?:tj)|(?:tk)|(?:tl)|(?:tm)|(?:tn)|(?:to)|(?:tp)|(?:tr)|(?:tt)|(?:tv)|(?:tw)|(?:tz)|(?:ua)|(?:ug)|(?:uk)|(?:us)|(?:uy)|(?:uz)|(?:va)|(?:vc)|(?:ve)|(?:vg)|(?:vi)|(?:vn)|(?:vu)|(?:wf)|(?:ws)|(?:ye)|(?:yt)|(?:za)|(?:zm)|(?:zw))(?:/[^\s()<>]+[^\s`!()\[\]{};:\'".,<>?\xab\xbb\u201c\u201d\u2018\u2019])?)', True, ()),                             
    ("EMAIL_ADDRESS"   , "([a-z0-9!#$%&'*+\/=?^_`{|.}~-]+@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)", False, ()), #should be first or second
    ("USER_NAME"       , "^[a-z0-9](@[a-z0-9!#$%&'*+\/=?^_`{|.}~-]+)", True, ()),
    ("DATE"            , '(?:(?<!\:)(?<!\:\d)[0-3]?\d(?:st|nd|rd|th)?\s+(?:of\s+)?(?:jan\.?|january|feb\.?|february|mar\.?|march|apr\.?|april|may|jun\.?|june|jul\.?|july|aug\.?|august|sep\.?|september|oct\.?|october|nov\.?|november|dec\.?|december)|(?:jan\.?|january|feb\.?|february|mar\.?|march|apr\.?|april|may|jun\.?|june|jul\.?|july|aug\.?|august|sep\.?|september|oct\.?|october|nov\.?|november|dec\.?|december)\s+(?<!\:)(?<!\:\d)[0-3]?\d(?:st|nd|rd|th)?)(?:\,)?\s*(?:\d{4})?|[0-3]?\d[-\./][0-3]?\d[-\./]\d{2,4}', True, ()),
    ("TIME"            , '\d{1,2}:\d{2} ?(?:[ap]\.?m\.?)?|\d[ap]\.?m\.?', False, ()),
    ("PHONE_NUMBER"    , '''((?:(?<![\d-])(?:\+?\d{1,3}[-.\s*]?)?(?:\(?\d{3}\)?[-.\s*]?)?\d{3}[-.\s*]?\d{4}(?![\d-]))|(?:(?<![\d-])(?:(?:\(\+?\d{2}\))|(?:\+?\d{2}))\s*\d{2}\s*\d{3}\s*\d{4}(?![\d-])))''', False, ()),
    ("PHONE_NUMBER"    , '((?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*(?:[2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|(?:[2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?(?:[2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?(?:[0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(?:\d+)?))', False, ()),
    ("IP_ADDRESS"      , '(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)', True, ()),
    ("IP_ADDRESS"      , '\s*(?!.*::.*::)(?:(?!:)|:(?=:))(?:[0-9a-f]{0,4}(?:(?<=::)|(?<!::):)){6}(?:[0-9a-f]{0,4}(?:(?<=::)|(?<!::):)[0-9a-f]{0,4}(?:(?<=::)|(?<!:)|(?<=:)(?<!::):)|(?:25[0-4]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-4]|2[0-4]\d|1\d\d|[1-9]?\d)){3})\s*', True, ()), # re.VERBOSE|re.IGNORECASE|re.DOTALL
    ("PRICE"           , '[$]\s?[+-]?[0-9]{1,3}(?:(?:,?[0-9]{3}))*(?:\.[0-9]{1,2})?', False, ()),
    ("CREDIT_CARD"     , '((?:(?:\\d{4}[- ]?){3}\\d{4}|\\d{15,16}))(?![\\d])', False, ()),
    ("CRYPTO"          , '(?<![a-km-zA-HJ-NP-Z0-9])[13][a-km-zA-HJ-NP-Z0-9]{26,33}(?![a-km-zA-HJ-NP-Z0-9])', False, ()),
    ("STREET_ADDRESS"  , '\d{1,4} [\w\s]{1,20}(?:street|st|avenue|ave|road|rd|highway|hwy|square|sq|trail|trl|drive|dr|court|ct|park|parkway|pkwy|circle|cir|boulevard|blvd)\W?(?=\s|$)', True, ()),
    ("STREET_ADDRESS"  , '\b\d{5}(?:[-\s]\d{4})?\b', False, ()),
    ("STREET_ADDRESS"  , 'P\.? ?O\.? Box \d+', True, ()),
    ("GOVT_ID"         , '(?!000|666|333)0*(?:[0-6][0-9][0-9]|[0-7][0-6][0-9]|[0-7][0-7][0-2])[- ](?!00)[0-9]{2}[- ](?!0000)[0-9]{4}', False, ()),
    ("ICD_CODE"        , '[A-TV-Z][0-9][A-Z0-9](\.[A-Z0-9]{1,4})', True, ())
  ]

    
  bantu_surnames = ["Dlamini", "Gumede", "Hadebe", "Ilunga", "Kamau", "Khoza", "Lubega", "M'Bala", "Mabaso", "Mabika", "Mabizela", "Mabunda", "Mabuza", "Macharia", "Madima", "Madondo", "Mahlangu", "Maidza", "Makhanya", "Malewezi", "Mamba", "Mandanda", "Mandlate", "Mangwana", "Manjate", "Maponyane", "Mapunda", "Maraire", "Masango", "Maseko", "Masemola", "Masengo", "Mashabane", "Masire", "Masondo", "Masuku", "Mataka", "Matovu", "Mbala", "Mbatha", "Mbugua", "Mchunu", "Mkhize", "Mofokeng", "Mokonyane", "Mutombo", "Ncube", "Ndagire", "Ndhlovu", "Ndikumana", "Ndiritu", "Ndlovu", "Ndzinisa", "Ngcobo", "Nkomo", "Nkosi", "Nkurunziza", "Radebe", "Tshabalala", "Tshivhumbe", "Vila"]
  
  
  langs = {
        "af": "Afrikaans",
        "als": "Tosk Albanian",
        "am": "Amharic",
        "an": "Aragonese",
        "ar": "Arabic",
        "arz": "Egyptian Arabic",
        "ast": "Asturian",
        "as": "Assamese",
        "av": "Avaric",
        "azb": "South Azerbaijani",
        "az": "Azerbaijani",
        "bar": "Bavarian",
        "ba": "Bashkir",
        "bcl": "Central Bikol",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bh": "Bihari",
        "bn": "Bengali",
        "bo": "Tibetan",
        "bpy": "Bishnupriya",
        "br": "Breton",
        "bs": "Bosnian",
        "bxr": "Russia Buriat",
        "ca": "Catalan",
        "cbk": "Chavacano",
        "ceb": "Cebuano",
        "ce": "Chechen",
        "ckb": "Central Kurdish",
        "cs": "Czech",
        "cv": "Chuvash",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "diq": "Dimli",
        "dsb": "Lower Sorbian",
        "dv": "Dhivehi",
        "el": "Modern Greek",
        "eml": "Emilian-Romagnol",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "frr": "Northern Frisian",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gn": "Guarani",
        "gom": "Goan Konkani",
        "gu": "Gujarati",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "hsb": "Upper Sorbian",
        "ht": "Haitian",
        "hu": "Hungarian",
        "hy": "Armenian",
        "ia": "Interlingua",
        "id": "Indonesian",
        "ie": "Interlingue",
        "ilo": "Iloko",
        "io": "Ido",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jbo": "Lojban",
        "jv": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Central Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "krc": "Karachay-Balkar",
        "ku": "Kurdish",
        "kv": "Komi",
        "kw": "Cornish",
        "ky": "Kirghiz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lez": "Lezghian",
        "li": "Limburgan",
        "lmo": "Lombard",
        "lo": "Lao",
        "lrc": "Northern Luri",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mai": "Maithili",
        "mg": "Malagasy",
        "mhr": "Eastern Mari",
        "min": "Minangkabau",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mrj": "Western Mari",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "mwl": "Mirandese",
        "my": "Burmese",
        "myv": "Erzya",
        "mzn": "Mazanderani",
        "nah": "Nahuatl", # languages
        "nap": "Neapolitan",
        "nds": "Low German",
        "ne": "Nepali",
        "new": "Newari",
        "nl": "Dutch",
        "nn": "Norwegian Nynorsk",
        "no": "Norwegian",
        "oc": "Occitan",
        "or": "Oriya",
        "os": "Ossetian",
        "pam": "Pampanga",
        "pa": "Panjabi",
        "pl": "Polish",
        "pms": "Piemontese",
        "pnb": "Western Panjabi",
        "ps": "Pushto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "rm": "Romansh",
        "ro": "Romanian",
        "ru": "Russian",
        "sah": "Yakut",
        "sa": "Sanskrit",
        "scn": "Sicilian",
        "sd": "Sindhi",
        "sh": "Serbo-Croatian",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "tk": "Turkmen",
        "tl": "Tagalog",
        "tr": "Turkish",
        "tt": "Tatar",
        "tyv": "Tuvinian",
        "ug": "Uighur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vec": "Venetian",
        "vi": "Vietnamese",
        "vo": "Volapük",
        "war": "Waray",
        "wa": "Walloon",
        "wuu": "Wu Chinese",
        "xal": "Kalmyk",
        "xmf": "Mingrelian",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "yue": "Yue Chinese",
        "zh": "Chinese",
    }
  
  #adapted from https://github.com/christabor/faker_extras/blob/master/faker_extras/human.py, licensed under MIT License
  person2religion = {
            'Atheist': 'Atheism',
            'Christian': 'Christianity',
            'Muslim': 'Islam',
            'Hindu': 'Hinduism',
            'Buddhist': 'Buddhism',
            'Sikh': 'Sikhism',
            'Jew': 'Judaism',
            "Bahá'í": 'Bahaism',
            'Confucianists': 'Confucianism',
            'Jain': 'Jainism',
            'Shintoists': 'Shintoism',
            'Catholic': 'Catholicism',
            'Mormon': 'mormon_church',
  }

  religion_list =  ['christianity', 'mandaeism','adventism', 'sunni_islam',   ]
  religious_member_list = ['muhammaden','portuguese_jesuits', 'augustine', 'hindustani',  'paynim',  'muslem', 'muhammadan', 'mohammedan', 'muslim_believer', 'islamic', 'mussulman' ]

  # from https://github.com/uclanlp/corefBias/blob/master/WinoBias/wino/data/female_occupations.txt which is under MIT license
  # use for adding into all jobs list. consider what else we can do with this list.
  jobs = [
        'attendant',
        'cashier',
        'teacher',
        'nurse',
        'assistant',
        'secretary',
        'auditor',
        'cleaner',
        'receptionist',
        'clerk',
        'counselor',
        'designer',
        'hairdresser',
        'writer',
        'housekeeper',
        'baker',
        'accountant',
        'editor',
        'librarian',
        'tailor',                
        'driver',
        'supervisor',
        'janitor',
        'cook',
        'laborer',
        'construction worker',
        'chief',
        'developer',
        'carpenter',
        'manager',
        'lawyer',
        'farmer',
        'salesperson',
        'physician',
        'guard',
        'analyst',
        'mechanic',
        'sheriff',
        'CEO',
        'air_marshal',  'messenger', 'adviser', 'school_superintendent', 'rancher', 'air_vice_marshal', 'rear_admiral_upper_half', 'rear_admiral_lower_half', 'keyboarder', 'restaurateur', 
        'gamekeeper', 'maid_servant', 'merchant', 'boss', 'director', 'organizer', 'trustee', 'coordinator', 'case_officer', 'government_official', 'film_director', 'superintendent', 'concierge', 'custodian', 'babyminder', 'carer', \
        'dramaturge', 'worker', 'errand_boy', 'bishop', 'bearer', 'herald', 'forwarding_merchant',  'civil_law_notary', 'public_procurator', 'crown_prosecutor', 'attorney_general', \
        'railway_worker', 'counterfeiter', 'radiologic_technologist', 'glassmaker', 'authoress', 'promotional_model', 'booth_babe', 'anaesthesiologist', \
        'treasurer', 'bank_manager',  'garbage_collector', 'scavenger',  'road_sweeper',  'painter_supported_by_patron', 'performer',  'plowwoman', \
        'private_secretary',  'cosmetologist', 'beauty_consultant', 'general_of_army', 'air_chief_marshal', 'eye_specialist', 'tradesman', \
        'attendant_male_servant', 'domestic_worker',  'squadron_leader', 'earl_marshal', 'sculptor', 'croupier',  'encyclopedist', \
        'dispensing_chemist', 'nanny',  'healer', 'person_who_gives_therapy', 'armor_maker', 'weaponsmith', \
        'subordinate_official', 'rikishi_of_lowest_rank',  'rescuer', 'cartoonist', 'interior_designer', 'couturier', 'planner', \
        'japanese_military_officer', 'non_commissioned_officer', 'bondman', 'leader', 'directress', 'directrix', \
        'agent_responsible_for_goods', 'lord_high_steward', 'postwoman', 'postal_carrier', 'lady_in_waiting',\
        'harvestman', 'thresher', 'policeman', 'transcriber',  'scorekeeper', 'bookkeeper', 'scriber', \
        'privy_councillor', 'babysitter', 'wet_nurse',  'au_pair',  'ruler', 'governor', 'infantryman',  'bursar', 'accounting_clerk', \
        'chief_librarian', 'helmsman', 'officer', 'inventor', 'marshall', \
        'marshal', 'air_commodore', 'general_practitioner', 'workman',  'woodworker',  'trader', 'salesman', 'serviceman', \
        'coach', 'managing_director', 'overseer', 'conductor', 'receiver', 'managing', 'operator', 'landlord',  'warden', 'chef',\
        'regent', 'commissioner', 'admin','headmaster', 'president', 'magistrate', 'health_professional',  'chauffeur', 'gardener', \
        'courier', 'deliveryman', 'conveyer', 'pallbearer', 'speaker', 'fire_warden', 'caregiver', 'public_notary', 'attorney', \
        'blacksmith', 'painter', 'artiste', 'author', 'composer', 'entertainer', 'first_sergeant', 'beautician', 'maidservant', 'servant',
        'server', 'runner_before_carriage', 'manservant', 'dining_room_attendant', 'commanding_officer', 'colonel', 'commandant', 'engraver', \
        'emissary', 'drawer', 'modeler', 'maid', 'flight_attendant', 'waiter', 'guide', 'executive', 'foreman', 'mediator', 'peacemaker',\
        'obstetrician', 'doc', 'accoucheur', 'bank_proprietor', 'impresario', \
        'penman',  'collector', 'politruk', 'coolie', 'tinkerer', 'boilermaker', 'maid_of_honour', 'printer',\
        'artisan',  'labourer',  'express_messenger', 'expressman', 'bureaucrat',  'yachter', 'academician', 'professor', 'instructor', \
        'spokesman', 'rabbi', 'postal_delivery_worker', 'apothecary', 'druggist', 'forester', 'record_keeper', 'chronicler', \
        'herder', 'sketcher', 'tap_dancer', 'public_prosecutor', 'prosecutor', 'advisor', 'consultant', 'watchmaker', 'commissionaire', \
        'doorman', 'taskmaster', 'maintenance_man', 'goalkeeper', 'cabinet_minister', 'secretary_of_state', 'principal', 'council_member', \
        'sub_lieutenant', 'launderer', 'breeder', 'talent_scout', 'washer', 'guru', 'dayworker', 'safebreaker', \
        'garage_mechanic', 'wharfie', 'comedian', 'player', 'actress', 'creator', 'spokesperson', 'actor_or_actress', 'aviator', \
        'medically_qualified_psychoanalyst', 'management_consultancy', 'journeyman', 'finisher',
    ]

  #from https://en.wikipedia.org/wiki/List_of_labor_unions_in_the_United_States which is licensed under Creative Commons Attribution-ShareAlike License
  union_list =[
      "National Education Association of the United States",
      "NEA",
      "Service Employees International Union",
      "SEIU",
      "American Federation of State, County, and Municipal Employees",
      "AFSCME",
      "Teamsters",
      "United Food and Commercial Workers",
      "United Auto Workers",
      "UAW",
      "United Steelworkers",
      "USW",
      "American Federation of Teachers",
      "AFT",
      "International Brotherhood of Electrical Workers",
      "IBEW",
      "Laborers' International Union of North America",
      "LIUNA",
      "International Association of Machinists and Aerospace Workers",
      "IAM",
      "Communications Workers of America",
      "CWA",
      "United Brotherhood of Carpenters and Joiners of America",
      "International Longshore and Warehouse Union",
      "International Union of Operating Engineers",
      "United Association",
      "National Association of Letter Carriers",
      "NALC",
      "American Federation of Government Employees",
      "AFGE",
      "American Postal Workers Union",
      "International Association of Fire Fighters",
      "UNITE HERE",
      "National Postal Mail Handlers Union",
      "Amalgamated Transit Union",
      "American Nurses Association",
      "International Alliance of Theatrical Stage Employees",
      "IATSE",
      "Sheet Metal Workers International Association",
      "International Union of Painters and Allied Trades",
      "International Association of Bridge, Structural, Ornamental, and Reinforcing Iron Workers",
      "Transport Workers Union of America",
      "National Rural Letter Carriers' Association",
      'international_telecommunication_union',
      'universal_postal_union',
      'students_union',
      'trade_union',
      'prisoners_union',
      'labor_union',
      'police_trade_union',
      'police_union',
      'protestant_union',
      'art_union',
      'enterprise_union',
      'labour_union',
      'trades_union',
      'teamsters_union',
      'craft_union',
      'student_union',
      'industrial_union',
      'company_union',
      'christian_democratic_union',
      'closed_union',
      'general_union',
      'european_broadcasting_union',
      'international_telecommunications_union',
      'in_house_union',
      'workers_credit_union',
      'national_railway_motive_power_union',
      'local_labor_union',
      'local_labour_union',
      'joint_labor_union',
      'joint_labour_union',
      'national_railway_workers_union',
      'teachers_union',
      "seamen's_union",
      'japan_coal_miners_union',
      'real_union',
      'vertical_union',
      'rival_labor_union',
      'rival_labour_union',
      'horizontal_union',
      'employees_union',
      'yellow_union',
      'beggars_union',
      'international_mathematical_union',
      'federal_union',
      'arab_telecommunication_union',
      'itu', 'professional_association']

  #adapted from https://github.com/christabor/faker_extras/blob/master/faker_extras/human.py, licensed under MIT License
  race_list = [
            'Aboriginal',
            'Australian',
            'South Pacific',
            'Aborigine',
            'African',
            'African-American',
            'American',
            'American Indian',
            'Arabian',
            'Arabic',
            'Arab',
            'Middle Eastern',
            'Asian',
            'Asian-American',
            'Asian Indian',
            'Asian Mongoloid',
            'Asian Subcontinent',
            'Asian Pacific',
            'Bi-multiracial',
            'African descent',
            'Black Person',
            'African-American',
            'Central-Southern African',
            'Brown Person',
            'Hispanic',
            'Chinese',
            'Eastern Indian',
            'Eskimo',
            'Aleutian',
            'European',
            'Filipino',
            'Hispanic',
            'Indian',
            'Middle Asian',
            'Pakistani',
            'Islander',
            'Japanese',
            'Jewish',
            'Korean',
            'Latina',
            'Latino',
            'Mestiza',
            #'Mixed',
            'Mexican',
            'Middle Eastern',
            'Native American',
            'Aborigine',
            'Indigenous People',
            'Pacific Islander',
            'East Asian',
            'Polynesian',
            'Pacific Islander',
            'South American',
            'Latin American',
            'Vietnamese',
            'White',
            'Caucasian',
            'European',
            'Northern European',
            'americans', 
            'white_man_or_woman', 
            'turk',  'irishman', 'kazakh', 'north_korean', 'frenchman', 'south_korean', 'sassenach', 
            'irish', 'frenchwoman', 'french', 'arabian_people', 'amerind', 'arabo', 'arabia', 'arabs', 'arabize', 'negro',\
            'hispanic_american', 'latin', 'white_person',  'australian_aborigine', 'amerindian', 'indigenous_peoples_of_americas', 'amerind' \
            'arabian_people', 'black_people', 'native_people', 'indigenous_peoples',  'autochthon','red_indian', 'spanish', \
            'irelander', 'frenchlike', 'icelandic', 'irishwoman',
        ]
        
  #from https://www.cdc.gov/diseasesconditions/az/z.html
  #plus data mined from conceptnet
  disease_list = [
            'ADHD',
            'Arthritis',
            'Asthma',
            'Autism',
            'Avian Influenza',
            'Birth Defects',
            'Cancer',
            'Chlamydia',
            'Chronic Fatigue Syndrome',
            'Chronic Obstructive Pulmonary Disease',
            'COPD',
            'COVID-19',
            'Diabetes',
            'Ebola',
            'Ebola Virus Disease',
            'Epilepsy',
            'Fetal Alcohol Spectrum Disorder',
            'Flu',
            'Influenza',
            'Genital Herpes',
            'Herpes Simplex Virus',
            'Giardiasis',
            'Gonorrhea',
            #'Healthy Water # not sure if this is a disease or health condition
            'Heart Disease',
            'Hepatitis',
            'HIV',
            'AIDS',
            'Human papillomavirus',
            'HPV',
            'Kidney Disease',
            'Chronic Kidney Disease',
            'Meningitis',
            'Methicillin-resistant Staphylococcus aureus',
            'MRSA',
            'Microcephaly',
            'Middle East Respiratory Syndrome',
            'MERS',
            'Overweight',
            'Obesity',
            'Parasites',
            'Scabies',
            'Salmonella',
            'Sexually Transmitted Diseases',
            'Stroke',
            'Traumatic Brain Injury',
            'TBI',
            'Trichomonas Infection',
            'Trichomoniasis',
            'Tuberculosis',
            'TB',
            'Zika Virus',
            'malignant_tumour', 'diabetic', 'urine_sugar', 'sugar_diabetes', 'ehf', 'evd', 'epileptic', 'flue', 'hsv', 'blennorrhoea', \
            'gonorrheal_infection', 'corpulence', 'adiposity',  'ringworm', 'leper',  'cerebral_haemorrhage', \
            'suffer_paralyzing_stroke',  'seizure', 'phthisic', 'abnormity', 'disfigurement',  \
            'intellectual_disability', 'morbid_dependence', 'be_poisoned',  'malaise', \
            'adiaphoresis', 'choke','shed_blood', 'pathologic', 'meteorism', 'slight_illness',\
            'thrombosis',  'alcohol_intoxication', 'heavily_intoxicated', 'undescended_testicle','varicose_veins',
            'alopecia', 'fall_ill', 'diseased', 
            'female_infertility', 'blennorrhea', 
            "madelung's_deformity", 'alcohol_poisoning', 'pandemic', 'epidemic', 'heat_stroke', 
            'pathological_changes','fainting_spell', 'oxygen_deficiency','blister', 'eschar', 'black_fever', 
            'paise', 'hemorrhage_fever', 'bubonic', 'alexic','spinal_disc_herniation','friction_burn', 'marring_caused_by_rubbing', 
            'suffering_from_heat','eburnation', 'phytophthora_infestans', 'local_disease', 'exanthem_subitum','blood_congestion','azotemic', 
            'hyperferremia', 'lymph_node_enlargement', 'periodentosis', 'pressure_ulcer', 'bruising', 'luxation', 'dementia',  'post_traumatic_stress_disorder', 
            'bone_fracture', 'mastocarcinoma','dissociative_identity_disorder', 'concussion', 'extravasated_blood', 'hysterics', 'female_hysteria', 'bowel_obstruction',  
            'streptococcal_throat_infection', 'tetanic', 'cow_pox','achromatopia','dysrhythmia', 'irregular_pulse', 'color_blind', 'uniocular_dichromat', 'down’s_syndrome', 
            'polydactylism', 'nicotinism', 'hunchbacked', 'humpbacked', 'crookback', 'dipsomania', 'inebriety','travel_sickness','mareo', 'sea_sickness', 'wilms_tumor','anorexic', 
            'bulimia_nervosa', 'binge_eating','binge_drinking',  'sickness_from_anxiety','undernourish', 'undernutrition', 'acute_mountain_sickness','wasting_syndrome',
   
        ]
        

  #TODO, add in age range
  pronoun2gender = {
      "they": ['homosexual', 
          'bisexual', 
          'transgender', 
          'nonbinary_person',
          'gay_person',
          'homosexuals', 
          'bisexuals', 
          'transgenders', ],
      "he": ['gay_man', 'transgender_man',
          'little_boy', 
          'chap',  
          'laddie', 
          'male_compatriot',  
          'boy',
          'guy',
          'male',
          'gentleman',
          'man',
          'dude',
          'lad',],
      "she": ['lesbian',
          'transgender_woman', 
          'gay_woman',
          'female_child',
          'fair_sex', 
          'female_compatriot', 
          'young_unmarried_woman',  
          'woman',
          'gal',
          'lady',
          'female',
          'girl',
          'mademoiselle',  'elder_sister', 
          'maiden', 'senorita',  'maid', 'little_girl', 'young_female_rice_planter', 'virgin_female', 
          'adolescent_female', 'lassie', 'dame', 'damsel','pucelle', 'miss', 
          'older_sister'
          ]
  }

  #other plural gender nouns
  gender_list = [ 'nonbinary_people',
          'gay_people', 'gay_men', 'transgender_men',
          'little_boys', 
          'chaps',  
          'laddies', 
          'male_compatriots',  
          'boys',
          'guys',
          'males',
          'gentlemen',
          'men',
          'dudes',
          'lads', 
          'lesbiasn',
          'transgender_women', 
          'gay_women',
          'female_children',
          'fair_sexes', 
          'female_compatriots', 
          'young_unmarried_women',  
          'women',
          'gals',
          'ladies',
          'females',
          'girls',
          'lasses',
          'ladies_and_gentlemen'
  ] 

  pronoun2pronoun = {'he': ['he', 'his', 'himself', 'him'], 'she': ['she', 'her',  'hers', 'herself'], \
                    'they': ['they', 'them', 'themsleves', 'theirs', 'their',], 'it': ['it', 'its','itself','that', 'that_one', 'this', 'those', 'these', ]}
  pronoun2title = {'he':['sir', 'mister',"mr.", "mr"], "she": ["mrs.", "miss.", "mrs", 'ma_am', 'maam', "ma'am", 'missus', ]}
  person_pronoun_list = ['her', 'she',  'hers', 'herself', 'his', 'he', 'himself', 'him', 'yours', 'mine', 'ours', 'my', "one's", 'our', 'you', 'your', "one's_own", 'by_oneself', 'y_all', 'that_person', 'yourself',  'thee', 'i', 'thy', 'we', 'me', 'thine', 'us', 'myself', 'ourselves', 'oneself', 'thou', 'yourselves',  "on_one's_own", 'themselves',  'i_or_me']
  other_pronoun_list = ['it', 'its', 'they', 'their', 'itself', 'them', 'theirs', 'this', 'those', 'these', 'this_one', 'that_one', 'that']
  title_list = [ 'ms.', 'maam', 'mrs.', "ma'am", 'ma_am', 'missus', 'sir','mr.', 'mister', ]


  # from https://github.com/uclanlp/corefBias/blob/master/WinoBias/wino/generalized_swaps.txt and
  # from https://github.com/uclanlp/corefBias/blob/master/WinoBias/wino/extra_gendered_words.txt which are licensed under MIT license
  female_to_male_gender_swap = {'abbess': 'abbot',
    'abbesses': 'abbots',
    'actress': 'actor',
    'actresses': 'actors',
    'adultress': 'adultor',
    'adultresses': 'adultors',
    'airwoman': 'airman',
    'airwomen': 'airmen',
    'aunt': 'uncle',
    'aunts': 'uncles',
    'barnoesses': 'barons',
    'baroness': 'baron',
    'barwoman': 'barman',
    'barwomen': 'barmen',
    'belle': 'beau',
    'belles': 'beaus',
    'bellgirl': 'bellboy',
    'bellgirls': 'bellboys',
    'bride': 'bridegroom',
    'brides': 'bridegrooms',
    'busgirl': 'busboy',
    'busgirls': 'busboys',
    'businesswoman': 'businessman',
    'businesswomen': 'businessmen',
    'camerawoman': 'cameraman',
    'camerawomen': 'cameramen',
    'chairwoman': 'chairman',
    'chairwomen': 'chairmen',
    'chick': 'dude',
    'chicks': 'dudes',
    'cowgirl': 'cowboy',
    'cowgirls': 'cowboys',
    'daughter': 'son',
    'daughters': 'sons',
    'duchess': 'duke',
    'duchesses': 'dukes',
    'empress': 'emperor',
    'empresses': 'emperors',
    'enchantress': 'enchanter',
    'female': 'male',
    'females': 'males',
    'fiancee': 'fiance',
    'fiancees': 'fiances',
    'gal': 'guy',
    'gals': 'guys',
    'girl': 'guy',
    'girls': 'guys',
    'godess': 'god',
    'godesses': 'gods',
    'governess': 'governor',
    'governesses': 'governors',
    'granddaughter': 'grandson',
    'granddaughters': 'grandsons',
    'grandmother': 'grandfather',
    'grandmothers': 'grandfathers',
    'headmistress': 'headmaster',
    'headmistresses': 'headmasters',
    'her': 'his',
    'heroine': 'hero',
    'heroines': 'heros',
    'hers': 'theirs',
    'herself': 'himself',
    'hostess': 'host',
    'hostesses': 'hosts',
    'ladies': 'lords',
    'lady': 'lord',
    'landladies': 'landlords',
    'landlady': 'landlord',
    'lass': 'lad',
    'lasses': 'lads',
    "ma'am": 'sir',
    'maam': 'sir',
    'maidservant': 'manservant',
    'maidservants': 'manservants',
    'marchioness': 'marquis',
    'masseuse': 'masseur',
    'masseuses': 'masseurs',
    'miss': 'sir',
    'mistress': 'master',
    'mistresses': 'masters',
    'mom': 'dad',
    'mommies': 'daddies',
    'mommy': 'daddy',
    'moms': 'dads',
    'mother': 'father',
    'mothers': 'fathers',
    'mrs.': 'mr.',
    'ms.': 'mr.',
    'niece': 'nephew',
    'nieces': 'nephews',
    'nun': 'monk',
    'nuns': 'monks',
    'policewoman': 'policeman',
    'priestess': 'priest',
    'priestesses': 'priests',
    'princess': 'prince',
    'princesses': 'princes',
    'queen': 'king',
    'queens': 'kings',
    'seamstress': 'tailors',
    'she': 'he',
    'sister': 'brother',
    'sisters': 'brothers',
    'sorceress': 'sorcerer',
    'sorceresses': 'sorcerers',
    'spinster': 'bachelor',
    'spinsters': 'bachelors',
    'spokeswoman': 'spokesman',
    'spokeswomen': 'spokesmen',
    'stepdaughter': 'stepson',
    'stepdaughters': 'stepsons',
    'stepmother': 'stepfather',
    'stepmothers': 'stepfathers',
    'stewardess': 'steward',
    'stewardesses': 'stewards',
    'waitress': 'waiter',
    'waitresses': 'waiters',
    'widow': 'widower',
    'widows': 'widowers',
    'wife': 'husband',
    'witch': 'wizard',
    'witches': 'wizards',
    'wives': 'husbands',
    'woman': 'man',
    'women': 'men'}

  male_to_female_gender_swap = {'abbot': 'abbess',
    'abbots': 'abbesses',
    'actor': 'actress',
    'actors': 'actresses',
    'adultor': 'adultress',
    'adultors': 'adultresses',
    'airman': 'airwoman',
    'airmen': 'airwomen',
    'bachelor': 'spinster',
    'bachelors': 'spinsters',
    'barman': 'barwoman',
    'barmen': 'barwomen',
    'baron': 'baroness',
    'barons': 'barnoesses',
    'beau': 'belle',
    'beaus': 'belles',
    'bellboy': 'bellgirl',
    'bellboys': 'bellgirls',
    'boy': 'girl',
    'boys': 'girls',
    'bridegroom': 'bride',
    'bridegrooms': 'brides',
    'brother': 'sister',
    'brothers': 'sisters',
    'busboy': 'busgirl',
    'busboys': 'busgirls',
    'businessman': 'businesswoman',
    'businessmen': 'businesswomen',
    'cameraman': 'camerawoman',
    'cameramen': 'camerawomen',
    'chairman': 'chairwoman',
    'chairmen': 'chairwomen',
    'cowboy': 'cowgirl',
    'cowboys': 'cowgirls',
    'dad': 'mom',
    'daddies': 'mommies',
    'daddy': 'mommy',
    'dads': 'moms',
    'dude': 'chick',
    'dudes': 'chicks',
    'duke': 'duchess',
    'dukes': 'duchesses',
    'emperor': 'empress',
    'emperors': 'empresses',
    'enchanter': 'enchantress',
    'father': 'mother',
    'fathers': 'mothers',
    'fiance': 'fiancee',
    'fiances': 'fiancees',
    'gentleman': 'lady',
    'gentlemen': 'ladies',
    'girl': 'boy',
    'god': 'godess',
    'gods': 'godesses',
    'governor': 'governess',
    'governors': 'governesses',
    'grandfather': 'grandmother',
    'grandfathers': 'grandmothers',
    'grandson': 'granddaughter',
    'grandsons': 'granddaughters',
    'groom': 'bride',
    'grooms': 'brides',
    'guy': 'girl',
    'guys': 'girls',
    'he': 'she',
    'headmaster': 'headmistress',
    'headmasters': 'headmistresses',
    'hero': 'heroine',
    'heros': 'heroines',
    'him': 'her',
    'himself': 'herself',
    'his': 'her',
    'host': 'hostess',
    'hosts': 'hostesses',
    'husband': 'wife',
    'husbands': 'wives',
    'king': 'queen',
    'kings': 'queens',
    'lad': 'lass',
    'lads': 'lasses',
    'landlord': 'landlady',
    'landlords': 'landladies',
    'lord': 'lady',
    'lords': 'ladies',
    'male': 'female',
    'males': 'females',
    'man': 'woman',
    'manservant': 'maidservant',
    'manservants': 'maidservants',
    'marquis': 'marchioness',
    'masseur': 'masseuse',
    'masseurs': 'masseuses',
    'master': 'mistress',
    'masters': 'mistresses',
    'men': 'women',
    'monk': 'nun',
    'monks': 'nuns',
    'mr.': 'ms.',
    'nephew': 'niece',
    'nephews': 'nieces',
    'policeman': 'policewoman',
    'priest': 'priestess',
    'priests': 'priestesses',
    'prince': 'princess',
    'princes': 'princesses',
    'sir': 'maam',
    'son': 'daughter',
    'sons': 'daughters',
    'sorcerer': 'sorceress',
    'sorcerers': 'sorceresses',
    'spokesman': 'spokeswoman',
    'spokesmen': 'spokeswomen',
    'stepfather': 'stepmother',
    'stepfathers': 'stepmothers',
    'stepson': 'stepdaughter',
    'stepsons': 'stepdaughters',
    'steward': 'stewardess',
    'stewards': 'stewardesses',
    'tailor': 'seamstress',
    'tailors': 'seamstress',
    'uncle': 'aunt',
    'uncles': 'aunts',
    'waiter': 'waitress',
    'waiters': 'waitresses',
    'widower': 'widow',
    'widowers': 'widows',
    'wizard': 'witch',
    'wizards': 'witches'}
  
  other_gender_swap = {
    'them': 'her',
    'their': 'her',
    'theirs': 'hers',
    'themself': 'herself',
    'they': 'she',
    'he': 'they',
    'him': 'them',
    'his': 'theirs',
    'himself': 'themself',
    'she': 'they',
    'her': 'their',
    'hers': 'theirs',
    'herself': 'themself',
  }

  political_party_list = ['labour_party',
    'conservative_party',
    'liberal_party',
    'national_party',
    'political_party',
    'socialist_party',
    'uk_independence_party',
    'republican_party',
    'democratic_party',
    "people's_party",
    'communist_party',
    'social_democratic_party',
    'democratic_republican_party',
    'nazi_party',
    'green_party',
    'australian_labor_party',
    'kurdistan_workers_party',
    'whig_party',
    'agrarian_party',
    'anti_masonic_party',
    'prohibition_party',
    'garden_party',
    'progressive_party',
    'democratic_socialist_party',
    'labor_party',
    'parliamentary_party',
    'member_of_green_party',
    'left_wing_party',
    'pirate_party',
    'governing_party',
    'ruling_party',
    'japan_socialist_party',
    'new_democratic_party',
    'progressive_conservative_party',
    'federalist_party',
    'american_labor_party',
    'states_rights_democratic_party',
    'american_party',
    'liberal_democrat_party',
    'national_socialist_german_workers_party',
    'socialist_labor_party',
    'grand_old_party',
    'scottish_national_party',
    'opposition_party',
    'australian_aussie_party',
    'ba_ath_party',
    'baath_party',
    'national_fascist_party',
    'fascist_party',
    'russian_communist_party',
    'government_party',
    'chinese_communist_party',
    'new_conservative_party',
    'leading_members_of_party',
    'membership_in_party',
    'joining_political_party',
    'justice_party',
    'new_clean_government_party',
    'secession_from_party',
    "worker's_party",
    'labor_farmer_party',
    'labour_farmer_party',
    'allied_political_party',
    'same_political_party',
    'constitutional_nationalist_party',
    "people's_new_party",
    'local_political_party',
    'majority_party',
    'minor_political_party',
    'small_political_party',
    'minority_party',
    'radical_political_party',
    'entire_political_party',
    'reform_party',
    'constitutional_reform_party',
    'political_fundraising_party',
    'new_political_party',
    'new_frontier_party',
    'new_korea_party',
    'japanese_communist_party',
    'japan_new_party',
    'japan_restoration_party',
    'democratic_liberal_party',
    'constitutional_democratic_party',
    'democratic_progressive_party',
    'okinawa_socialist_masses_party',
    'proletarian_party',
    'imperialist_party',
    'socialist_masses_party',
    'founding_political_party',
    'constitutional_imperial_rule_party',
    'liberal_democratic_party',
    'free_democratic_party',
    'military_clique_or_party',
    'moderate_party',
    'ruling_coalition_party',
    'opposition_coalition_party',
    'radical_party',
    'progressive_or_reformist_political_party',
    'rebel_party',
    'people_first_party',
    "people's_alliance_party",
    "people's_action_party",
    'pan_malaysian_islamic_party',
    'national_congress_party',
    'manifesto_of_communist_party',
    'peasant_party',
    'bharatiya_janata_party',
    'indian_congress_party',
    'guomindang_and_chinese_communist_party',
    'nationalist_party',
    'christian_democratic_party',
    'south_korean_grand_national_party',
    'workers_party',
    "kurdistan_worker's_party",
    'tory_party',
    'reformist_party',
    'justicialist_party',
    'soviet_communist_party',
    'guomindang_or_kuomintang', 'nationalsozialistische_deutsche_arbeiterpartei', 'political_opposition', 'new_komeito']

  political_party_member_list = ['communistic', 'bolshie']

  org_list = ['australian_football_league', 'north_atlantic_treaty_organisation', 'royal_marines', 'social_democrats', 'national_tax_agency', 'patent_agency', 'us_central_intelligence_agency', 'nationaol_science_foundation', 'intelligence_service'] 
  
  soc_eco_class_list = ['immigrant_class',
    'upper_lower_class',
    'middle_class',
    'working_class',
    'third_class',
    'lower_middle_class',
    'upper_lower_class',
    'upper_lower_class',
    'educated_class',
    'executive_class',
    'service_class',
    'low_class',
    'low_income_class',
    'propertied_class',
    'leisured_class',
    'warrior_class',
    'proletarian_class',
    'privileged_class'
    'intellectual_class',
    'wealthy_merchant_class',
    'high_and_low_class',
    'noble_class',
    'capitalist_class',
    'peasant_class',
    'land_owning_class',
    'proletarian_class', 
    'philistinism', 'highbrow', 'aristocrat', 'upper_classes', 'petty_bourgeois', 'nobleness', 'proletariat', 'bourgeoisie', 'upper_class', 'nobility', 'elite',  'ennoblement', 'upper_crust', 'gentry', 'working_class', 'aristocracy']
    

  public_figure_list = ['saint_lawrence', 'fryderyk_franciszek_chopin', 'benedick', 'skinner', 'davit', 'taylor', 'henri', 'harry', 'hal', 'francois_jacob', 'giacomo', 'greg', 'laurence', 'kelly', 'dewey', 'pedro', 'hussein', 'antony', 'hillary_rodham_clinton', 'curia', 'browne', 'andersen', 'rogers', 'octavius', 'alfredo', 'wright', 'st_lawrence', 'lawrence', 'clive_staples_lewis', 'lewis', 'lewis_gun', 'fitzgerald', 'elizabeth', 'president_george_w_bush', 'gandhi', 'crawford', 'davis', 'armstrong', 'sugar_ray_robinson', 'robinson', 'edward', 'duke_of_windsor', 'huxley', 'sully', 'hardy', 'goncourt', 'zeno', 'wilson', 'angus_frank_johnstone_wilson', 'alexander_wilson', 'george', 'burns', 'lambert', 'gustav', 'danton_true_young', 'beaumont', 'agrippina', 'bailey', 'ford', 'edsel_bryant_ford', 'ford_hermann_hueffer', 'lea', 'rose_louise_hovick', 'lighthorse_harry_lee', 'poutine', 'jackson', 'marshall', 'justinian', 'swift', 'strauss', 'holmes', 'castro', 'benedict', 'hughes', 'morris', 'otis_skinner', 'ernst_boris_chain', 'newman', 'gilbert', 'hablot_knight_browne', 'tucker', 'carter', 'williams', 'jones', 'bruce', 'mccarthy', 'calvin', 'david', 'william_of_orange', 'virgil_garnett_thomson', 'thomson', 'thomas', 'miller', 'clinton', 'irving', 'president_taylor', 'robert', 'roberts', 'lily', 'stevens', 'édouard', 'saint_james_apostle', 'jacques', 'jacob', 'bunyan', 'smith', 'captain_john_smith', 'dame_myra_hess', 'scott', 'lee', 'henry', 'warren', 'russell', 'whitman', 'howard', 'carnegie', 'wolfe', 'watson', 'bernoulli', 'morgan', 'abelard', 'pliny', 'cornell', 'taffeta', 'tuft', 'gregory_great', 'gregory', 'st_gregory_of_nazianzen', 'parkinson', 'princess_grace_of_monaco', 'pavlov', 'surname_nixon', 'goebbels', 'first_viscount_haldane_of_cloan', 'holden', 'hoffman', 'ernst_theodor_amadeus_hoffmann', 'franklin', 'bush', 'peter', 'evans', 'huntington', 'reich', 'frank', 'townsend_harris', 'octavian', 'husayn', 'charles', 'owen', 'anderson', 'admiral_dewey', 'muller', 'guggenheim', 'fairbanks', 'alfred', 'simpson', 'stravinsky', 'curie', 'constantine', 'antonius', 'noguchi', 'sherman', 'ernst_heinrich_weber', 'weber', 'schiaparelli', 'schumann', 'stewart', 'steward', 'hertz', 'fleming', 'gardner', 'mae_west', 'virginia_katherine_mcmath', 'arnold', 'hawkins', 'frederic_chopin', 'marvin_neil_simon', 'arthur', 'cervantes', 'fyodor_mikhailovich_dostoevsky', 'shelley', 'sherry', 'hurrah', 'fuller']

  faker_list = ['ar_AA',
    'ar_PS',
    'ar_SA',
    'bg_BG',
    'cs_CZ',
    'de_AT',
    'de_CH',
    'de_DE',
    'dk_DK',
    'el_GR',
    'en_GB',
    'en_IE',
    'en_IN',
    'en_NZ',
    'en_TH',
    'en_US',
    'es_CA',
    'es_ES',
    'es_MX',
    'et_EE',
    'fa_IR',
    'fi_FI',
    'fr_CA',
    'fr_CH',
    'fr_FR',
    'fr_QC',
    'ga_IE',
    'he_IL',
    'hi_IN',
    'hr_HR',
    'hu_HU',
    'hy_AM',
    'id_ID',
    'it_IT',
    'ja_JP',
    'ka_GE',
    'ko_KR',
    'lt_LT',
    'lv_LV',
    'ne_NP',
    'nl_NL',
    'no_NO',
    'or_IN',
    'pl_PL',
    'pt_BR',
    'pt_PT',
    'ro_RO',
    'ru_RU',
    'sl_SI',
    'sv_SE',
    'ta_IN',
    'th_TH',
    'tr_TR',
    'tw_GH',
    'uk_UA',
    'zh_CN',
    'zh_TW']
  strip_chars="-,~`!@#$%^&*(){}[]|\\/-_+=<>;:'\""

  yago_upper_ontology = {
    'ACCOMMODATION':  'FAC', 
    'ADMINISTRATIVE_AREA': 'GPE', 
    'AIRLINE':  'ORG',
    'AIRPORT':  'FAC', 
    'AMUSEMENT_PARK':  'FAC', 
    'ANATOMICAL_STRUCTURE': 'ANAT',
    'ANIMAL_SHELTER': 'FAC', 
    'APARTMENT':  'FAC', 
    'AQUARIUM':  'FAC', 
    'ARCHIVE_ORGANIZATION': 'ORG',
    'ARTERY': 'ANAT',
    'ARTICLE': 'WORK_OF_ART', 
    'ART_GALLERY':  'FAC', 
    'ATLAS': 'WORK_OF_ART', 
    'AUTOMOTIVE_BUSINESS': 'ORG',
    'AUTO_RENTAL': 'FAC', 
    'BAKERY':  'FAC', 
    'BANK_OR_CREDIT_UNION': 'ORG',
    'BAR_OR_PUB':  'FAC',
    'BEACH':  'LOCATION',
    'BEAUTY_SALON':  'FAC', 
    'BED_AND_BREAKFAST':   'FAC', 
    'BLOG': 'WORK_OF_ART', 
    'BLOG_POSTING': 'WORK_OF_ART', 
    'MEDICAL_PROCEDURE': 'MEDICAL_THERAPY',
    'BLOOD_TEST': 'MEDICAL_THERAPY',
    'BODY_OF_WATER':  'LOCATION',
    'BONE': 'ANAT',
    'BOOK':  'WORK_OF_ART',
    'BOOK_SERIES': 'WORK_OF_ART', 
    'BOOK_STORE':  'FAC', 
    'BOWLING_ALLEY':  'FAC', 
    'BRAND':   'ORG',
    'BREWERY':  'FAC', 
    'BRIDGE':  'FAC', 
    'BROADCAST_CHANNEL':  'ORG',
    'BROADCAST_SERVICE':  'PRODUCT',
    'BUDDHIST_TEMPLE':   'FAC', 
    'BUS_OR_COACH':'PRODUCT',
    'BUS_STATION': 'FAC',
    'BUS_STOP': 'FAC', 
    'CAFE_OR_COFFEE_SHOP': 'FAC', 
    'CAMPGROUND': 'FAC', 
    'CANAL':  'LOCATION',
    'CAR': 'PRODUCT',
    'CASINO': 'FAC', 
    'CATHOLIC_CHURCH': 'FAC', 
    'CEMETERY': 'FAC', 
    'CHAPTER': 'WORK_OF_ART',
    'CHILD_CARE':'PRODUCT',
    'CHURCH': 'FAC',
    'CITY': 'GPE', 
    'CITY_HALL':  'FAC',
    'CIVIC_STRUCTURE':  'FAC',
    'COLLECTION': 'WORK_OF_ART', 
    'COLLEGE_OR_UNIVERSITY': 'ORG',
    'COMEDY_CLUB': 'FAC', 
    'COMIC_SERIES': 'WORK_OF_ART',
    'COMIC_STORY':  'WORK_OF_ART', 
    'COMPUTER_LANGUAGE':  'LANGUAGE',
    'CONTINENT': 'LOCATION',
    'CORPORATION':  'ORG',
    'COUNTRY': 'GPE', 
    'COURSE': 'EVENT',
    'COURTHOUSE': 'FAC', 
    'CREATIVE_WORK': 'WORK_OF_ART', 
    'CREATIVE_WORK_SEASON': 'WORK_OF_ART',
    'CREATIVE_WORK_SERIES': 'WORK_OF_ART',
    'CREMATORIUM': 'FAC', 
    'DANCE_GROUP':  'ORG',
    'DATASET': 'WORK_OF_ART', 
    'DATA_CATALOG': 'WORK_OF_ART',
    'DAY_SPA':  'FAC', 
    'DEFENCE_ESTABLISHMENT':  'ORG',
    'DIAGNOSTIC_PROCEDURE': 'MEDICAL_THERAPY',
    'DISTILLERY': 'FAC', 
    'DRAWING':   'WORK_OF_ART', 
    'DRUG':  'PRODUCT',
    'DRUG_LEGAL_STATUS': 'LAW',
    'EDUCATIONAL_ORGANIZATION': 'ORG',
    'ELEMENTARY_SCHOOL': 'FAC',
    'EMBASSY': 'FAC',
    'EMERGENCY_SERVICE': 'PRODUCT',
    'EMPLOYMENT_AGENCY': 'ORG',
    'ENTERTAINMENT_BUSINESS': 'ORG',
    'EPISODE': 'WORK_OF_ART',
    'EVENT_SERIES': 'EVENT',
    'EVENT_VENUE': 'FAC',
    'FESTIVAL': 'EVENT',
    'FINANCIAL_PRODUCT': 'PRODUCT',
    'FINANCIAL_SERVICE': 'PRODUCT',
    'FIRE_STATION':  'FAC',
    'FOOD_ESTABLISHMENT': 'FAC',
    'GAME': 'PRODUCT',
    'GAS_STATION': 'FAC',
    'GENE': 'BIO_CHEM_ENTITY',
    'GOLF_COURSE': 'FAC',
    'GOVERNMENT_BUILDING':  'FAC',
    'GOVERNMENT_OFFICE':  'FAC',
    'GOVERNMENT_ORGANIZATION': 'ORG',
    'GROCERY_STORE': 'FAC',
    'HEALTH_AND_BEAUTY_BUSINESS': 'ORG',
    'HEALTH_CLUB': 'FAC',
    'HINDU_TEMPLE': 'FAC',
    'HOSPITAL': 'FAC',
    'HOSTEL': 'FAC',
    'HOTEL': 'FAC',
    'HOUSE': 'FAC',
    'ICE_CREAM_SHOP':'FAC',
    'INFECTIOUS_DISEASE': 'DISEASE',
    'JOINT': 'ANAT',
    'LAKE_BODY_OF_WATER': 'LOCATION',
    'LANDFORM': 'LOCATION',
    'LANDMARKS_OR_HISTORICAL_BUILDINGS': 'FAC',
    'LEGISLATION': 'LAW',
    'LIBRARY':'FAC',
    'LIGAMENT': 'ANAT',
    'LIQUOR_STORE':'FAC',
    'LOCAL_BUSINESS': 'ORG',
    'LODGING_BUSINESS': 'ORG',
    'MANUSCRIPT':  'WORK_OF_ART',
    'MAP': 'WORK_OF_ART',
    'MEDICAL_BUSINESS': 'ORG',
    'MEDICAL_CLINIC': 'FAC',
    'MEDICAL_DEVICE': 'PRODUCT',
    'MEDICAL_ENTITY': 'THING',
    'MEDICAL_GUIDELINE':  'WORK_OF_ART',
    'MEDICAL_ORGANIZATION': 'ORG',
    'MEDICAL_SIGN': 'MEDICAL_SYMPTOM',
    'MEDICAL_SIGN_OR_SYMPTOM': 'MEDICAL_SYMPTOM',
    'MEDICAL_SPECIALTY': 'JOB',
    'MEDICAL_TEST': 'MEDICAL_THERAPY',
    'MIDDLE_SCHOOL': 'FAC', 
    'MOBILE_APPLICATION': 'WORK_OF_ART',
    'MOLECULAR_ENTITY': 'BIO_CHEM_ENTITY',
    'MOSQUE': 'FAC',
    'MOTEL': 'FAC',
    'MOTORCYCLE': 'PRODUCT',
    'MOUNTAIN': 'LOCATION',
    'MOVIE': 'WORK_OF_ART',
    'MOVIE_THEATER':  'FAC', 
    'MUSCLE': 'ANAT',
    'MUSEUM':'FAC', 
    'MUSIC_ALBUM':  'WORK_OF_ART',
    'MUSIC_COMPOSITION':  'WORK_OF_ART',
    'MUSIC_GROUP': 'ORG',
    'MUSIC_PLAYLIST':  'WORK_OF_ART',
    'MUSIC_VENUE': 'FAC', 
    'NAIL_SALON':  'FAC', 
    'NERVE': 'ANAT',
    'NEWSPAPER':  'ORG',
    'NEWS_ARTICLE':  'WORK_OF_ART',
    'NIGHT_CLUB': 'FAC',
    'N_G_O': 'ORG',
    'OCCUPATION': 'JOB',
    'OCEAN_BODY_OF_WATER': 'LOCATION',
    'OPTICIAN': 'JOB',
    'ORGANIZATION': 'ORG',
    'OUTLET_STORE': 'FAC',
    'PAINTING': 'WORK_OF_ART',
    'PARK': 'LOC',
    'PARKING_FACILITY':  'FAC', 
    'PAWN_SHOP': 'FAC',
    'PERFORMING_ARTS_THEATER': 'FAC', 
    'PERFORMING_GROUP': 'ORG',
    'PERIODICAL': 'WORK_OF_ART',
    'PERSON': 'PERSON',
    'PET_STORE': 'FAC',
    'PHARMACY': 'FAC',
    'PHOTOGRAPH': 'WORK_OF_ART',
    'PHYSICAL_EXAM': 'MEDICAL_THERAPY',
    'PLACE': 'LOCATION',
    'PLACE_OF_WORSHIP': 'FAC',
    'PLAY': 'WORK_OF_ART',
    'PLAYGROUND': 'FAC', 
    'PODCAST_SERIES': 'WORK_OF_ART',
    'POLICE_STATION':  'FAC', 
    'POND': 'LOCATION',
    'POSTER': 'WORK_OF_ART',
    'POST_OFFICE':  'FAC', 
    'PRESCHOOL':  'FAC', 
    'PROTEIN': 'BIO_CHEM_ENTITY',
    'PUBLICATION_ISSUE': 'WORK_OF_ART',
    'PUBLICATION_VOLUME': 'WORK_OF_ART',
    'PUBLIC_SWIMMING_POOL': 'FAC',
    'PUBLIC_TOILET': 'FAC', 
    'RADIATION_THERAPY': 'MEDICAL_THERAPY',
    'RADIO_CHANNEL': 'ORG',
    'RADIO_SERIES': 'WORK_OF_ART',
    'RADIO_STATION':  'FAC', 
    'RATING': 'QUANTITY',
    'RECYCLING_CENTER': 'FAC', 
    'REPORT': 'WORK_OF_ART',
    'RESERVOIR': 'LOCATION',
    'RESORT': 'FAC',
    'RESTAURANT':  'FAC', 
    'RIVER_BODY_OF_WATER': 'LOCATION',
    'SCHOLARLY_ARTICLE': 'WORK_OF_ART',
    'SCHOOL': 'FAC', 
    'SCULPTURE': 'WORK_OF_ART',
    'SEA_BODY_OF_WATER': 'LOCATION',
    'SELF_STORAGE': 'PRODUCT',
    'SERVICE':'PRODUCT',
    'SHEET_MUSIC': 'WORK_OF_ART',
    'SHOE_STORE': 'FAC',
    'SHOPPING_CENTER':  'FAC', 
    'SKI_RESORT':  'FAC', 
    'SOCIAL_MEDIA_POSTING': 'WORK_OF_ART',
    'SOFTWARE_APPLICATION': 'WORK_OF_ART',
    'SPORTS_ACTIVITY_LOCATION':  'FAC', 
    'SPORTS_EVENT': 'EVENT',
    'SPORTS_ORGANIZATION': 'ORG',
    'SPORTS_TEAM': 'ORG',
    'STADIUM_OR_ARENA':  'FAC',
    'STATE':  'GPE', 
    'STORE':  'FAC', 
    'SUBWAY_STATION':  'FAC', 
    'SURGICAL_PROCEDURE': 'MEDICAL_THERAPY',
    'SYNAGOGUE': 'FAC', 
    'TATTOO_PARLOR': 'FAC', 
    'TAXON': 'ANIMAL',
    'TELEVISION_CHANNEL': 'ORG',
    'TELEVISION_STATION': 'FAC',
    'TENNIS_COMPLEX': 'FAC',
    'THEATER_GROUP': 'ORG',
    'THERAPEUTIC_PROCEDURE': 'MEDICAL_THERAPY',
    'THESIS': 'WORK_OF_ART',
    'TOURIST_ATTRACTION':  'FAC', 
    'TOURIST_INFORMATION_CENTER':  'FAC', 
    'TOY_STORE': 'FAC', 
    'TRAIN_STATION': 'FAC', 
    'TRAVEL_AGENCY': 'ORG',
    'T_V_EPISODE': 'WORK_OF_ART',
    'T_V_SEASON': 'WORK_OF_ART',
    'T_V_SERIES': 'WORK_OF_ART',
    'VEHICLE': 'PRODUCT',
    'VEIN': 'ANAT',
    'VIDEO_GAME': 'PRODUCT',
    'VIDEO_GAME_SERIES': 'EVENT',
    'VISUAL_ARTWORK': 'WORK_OF_ART',
    'VOLCANO': 'LOCATION',
    'WATERFALL': 'LOCATION',
    'WEB_PAGE': 'WORK_OF_ART',
    'WEB_SITE': 'DOMAIN_NAME',
    'WINERY': 'FAC',
    'WORKERS_UNION':  'UNION', 
    'ZOO': 'FAC'}
